development:
  adapter: postgresql
  database: BBSOfLee_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: BBSOfLee_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: BBSOfLee_production
  pool: 5
  timeout: 5000